/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetMyPageResponse
 */
export interface GetMyPageResponse {
  /**
   *
   * @type {string}
   * @memberof GetMyPageResponse
   */
  profileImageUrl?: string;
  /**
   *
   * @type {string}
   * @memberof GetMyPageResponse
   */
  nickname?: string;
  /**
   *
   * @type {string}
   * @memberof GetMyPageResponse
   */
  gender?: GetMyPageResponseGenderEnum;
  /**
   *
   * @type {string}
   * @memberof GetMyPageResponse
   */
  birthDate?: string;
  /**
   *
   * @type {string}
   * @memberof GetMyPageResponse
   */
  travelFrequency?: GetMyPageResponseTravelFrequencyEnum;
  /**
   *
   * @type {string}
   * @memberof GetMyPageResponse
   */
  planningType?: GetMyPageResponsePlanningTypeEnum;
  /**
   *
   * @type {string}
   * @memberof GetMyPageResponse
   */
  scheduleType?: GetMyPageResponseScheduleTypeEnum;
  /**
   *
   * @type {string}
   * @memberof GetMyPageResponse
   */
  hobby?: string;
  /**
   *
   * @type {string}
   * @memberof GetMyPageResponse
   */
  mbti?: GetMyPageResponseMbtiEnum;
  /**
   *
   * @type {string}
   * @memberof GetMyPageResponse
   */
  intro?: string;
}

export type GetMyPageResponseGenderEnum = "남성" | "여성";

export type GetMyPageResponseTravelFrequencyEnum =
  | "안가요!"
  | "1~3"
  | "4~6"
  | "7번 이상";

export type GetMyPageResponsePlanningTypeEnum = "계획적으로" | "즉흥적으로";

export type GetMyPageResponseScheduleTypeEnum = "빠듯하게" | "여유롭게";

export type GetMyPageResponseMbtiEnum =
  | "ISTJ"
  | "ISFJ"
  | "INFJ"
  | "INTJ"
  | "ISTP"
  | "ISFP"
  | "INFP"
  | "INTP"
  | "ESTP"
  | "ESFP"
  | "ENFP"
  | "ENTP"
  | "ESTJ"
  | "ESFJ"
  | "ENFJ"
  | "ENTJ";

/**
 *
 * @export
 * @interface UpdateMyPageInfoRequest
 */
export interface UpdateMyPageInfoRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateMyPageInfoRequest
   */
  travelFrequency?: UpdateMyPageInfoRequestTravelFrequencyEnum;
  /**
   *
   * @type {string}
   * @memberof UpdateMyPageInfoRequest
   */
  planningType?: UpdateMyPageInfoRequestPlanningTypeEnum;
  /**
   *
   * @type {string}
   * @memberof UpdateMyPageInfoRequest
   */
  scheduleType?: UpdateMyPageInfoRequestScheduleTypeEnum;
  /**
   *
   * @type {string}
   * @memberof UpdateMyPageInfoRequest
   */
  hobby?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateMyPageInfoRequest
   */
  mbti?: UpdateMyPageInfoRequestMbtiEnum;
  /**
   *
   * @type {string}
   * @memberof UpdateMyPageInfoRequest
   */
  intro?: string;
}

export type UpdateMyPageInfoRequestTravelFrequencyEnum =
  | "안가요!"
  | "1~3"
  | "4~6"
  | "7번 이상";

export type UpdateMyPageInfoRequestPlanningTypeEnum =
  | "계획적으로"
  | "즉흥적으로";

export type UpdateMyPageInfoRequestScheduleTypeEnum = "빠듯하게" | "여유롭게";

export type UpdateMyPageInfoRequestMbtiEnum =
  | "ISTJ"
  | "ISFJ"
  | "INFJ"
  | "INTJ"
  | "ISTP"
  | "ISFP"
  | "INFP"
  | "INTP"
  | "ESTP"
  | "ESFP"
  | "ENFP"
  | "ENTP"
  | "ESTJ"
  | "ESFJ"
  | "ENFJ"
  | "ENTJ";

/**
 *
 * @export
 * @interface UpdateNicknameRequest
 */
export interface UpdateNicknameRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateNicknameRequest
   */
  nickname: string;
}
